import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import dynamic from 'next/dynamic'

const PdfViewer = dynamic(() => import('@/components/PdfViewer'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>PDF Viewer Testing</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.title}>PDF Viewer Testing</h1>
        <p className={styles.description}>This is a test of the PDF viewer component.</p>
        <div className={styles.pdfContainer}>
          <PdfViewer fileUrl='files/sample.pdf' />
        </div>
      </main>
    </>
  )
}
